Committed changes recommended by instructor.
...I think I'm comitting manually since I can't figure out how to commit via Git on the CLI because Git and Github are monumentally !@#%@%#$% frustrating. Thank you Git for the helpful feedback:

Jerrys-MacBook-Pro:dasmoto jerryleclair$ git push origin master
To https://github.com/jerryleclair/dasmoto
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/jerryleclair/dasmoto'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I effing hate you.